# Generated by Django 4.2.1 on 2023-05-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appwrite_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_description', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_address', models.CharField(blank=True, max_length=100, null=True)),
                ('waiting_time', models.IntegerField(blank=True, null=True)),
                ('doctor_price', models.FloatField(blank=True, null=True)),
                ('from_time', models.CharField(max_length=100)),
                ('to_time', models.CharField(max_length=100)),
                ('Work_day', models.CharField(max_length=100)),
                ('appwrite_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital')),
            ],
        ),
    ]
