# Generated by Django 4.2.1 on 2023-05-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_doctor_hospital"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hospital",
            new_name="HospitalSection",
        ),
    ]
