# Generated by Django 3.2 on 2023-05-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_consultation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consultation_images'),
        ),
    ]
