from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    DoctorDetailsView,
    DoctorListAPIView,
    HospitalListAPIView,
    HospitalSectionListAPIView,
    LoginView,
    MyConsultationsView,
    MyReservationsView,
    ReplyToConsultationView,
    UserRegisterView,
)

urlpatterns = [
    path("", views.index, name='index'),
    path("add-department", views.addDep, name='addDep'),
    path("add-doctor", views.addDoc, name='addDoc'),
    path("add-hospital", views.addHos, name='addHos'),
    path("hospital1-department1", views.hospital1Dep1, name='hospital1Dep1'),
    path("hospital1-dep1-doc1-consultation", views.hospital1Dep1Doc1Consultation, name='hospital1Dep1Doc1Consultation'),
    path("hospital1-dep1-doc1-reservation", views.hospital1Dep1Doc1Reservation, name='hospital1Dep1Doc1Reservation'),
    path("hospital1-dep1-doc2-consultation", views.hospital1Dep1Doc2Consultation, name='hospital1Dep1Doc2Consultation'),
    path("hospital1-dep1-doc2-reservation", views.hospital1Dep1Doc2Reservation, name='hospital1Dep1Doc2Reservation'),
    path("hospital1-dep1-doc3-consultation", views.hospital1Dep1Doc3Consultation, name='hospital1Dep1Doc3Consultation'),
    path("hospital1-dep1-doc3-reservation", views.hospital1Dep1Doc3Reservation, name='hospital1Dep1Doc3Reservation'),
    path("hospital1-department2", views.hospital1Dep2, name='hospital1Dep2'),
    path("hospital1-dep2-doc1-consultation", views.hospital1Dep2Doc1Consultation, name='hospital1Dep2Doc1Consultation'),
    path("hospital1-dep2-doc1-reservation", views.hospital1Dep2Doc1Reservation, name='hospital1Dep2Doc1Reservation'),
    path("hospital1-dep2-doc2-consultation", views.hospital1Dep2Doc2Consultation, name='hospital1Dep2Doc2Consultation'),
    path("hospital1-dep2-doc2-reservation", views.hospital1Dep2Doc2Reservation, name='hospital1Dep2Doc2Reservation'),
    path("hospital1-department3", views.hospital1Dep3, name='hospital1Dep3'),
    path("hospital1-dep3-doc1-consultation", views.hospital1Dep3Doc1Consultation, name='hospital1Dep3Doc1Consultation'),
    path("hospital1-dep3-doc1-reservation", views.hospital1Dep3Doc1Reservation, name='hospital1Dep3Doc1Reservation'),
    path("hospital1-dep3-doc2-consultation", views.hospital1Dep3Doc2Consultation, name='hospital1Dep3Doc2Consultation'),
    path("hospital1-dep3-doc2-reservation", views.hospital1Dep3Doc2Reservation, name='hospital1Dep3Doc2Reservation'),
    path("hospital2-department1", views.hospital2Dep1, name='hospital2Dep1'),
    path("hospital2-dep1-doc1-consultation", views.hospital2Dep1Doc1Consultation, name='hospital2Dep1Doc1Consultation'),
    path("hospital2-dep1-doc1-reservation", views.hospital2Dep1Doc1Reservation, name='hospital2Dep1Doc1Reservation'),
    path("hospital2-dep1-doc2-consultation", views.hospital2Dep1Doc2Consultation, name='hospital2Dep1Doc2Consultation'),
    path("hospital2-dep1-doc2-reservation", views.hospital2Dep1Doc2Reservation, name='hospital2Dep1Doc2Reservation'),
    path("hospital2-dep1-doc3-consultation", views.hospital2Dep1Doc3Consultation, name='hospital2Dep1Doc3Consultation'),
    path("hospital2-dep1-doc3-reservation", views.hospital2Dep1Doc3Reservation, name='hospital2Dep1Doc3Reservation'),
    path("hospital2-department2", views.hospital2Dep2, name='hospital2Dep2'),
    path("hospital2-dep2-doc1-consultation", views.hospital2Dep2Doc1Consultation, name='hospital2Dep2Doc1Consultation'),
    path("hospital2-dep2-doc1-reservation", views.hospital2Dep2Doc1Reservation, name='hospital2Dep2Doc1Reservation'),
    path("hospital2-department3", views.hospital2Dep3, name='hospital2Dep3'),
    path("hospital2-dep3-doc1-consultation", views.hospital2Dep3Doc1Consultation, name='hospital2Dep3Doc1Consultation'),
    path("hospital2-dep3-doc1-reservation", views.hospital2Dep3Doc1Reservation, name='hospital2Dep3Doc1Reservation'),
    path("hospital2-department4", views.hospital2Dep4, name='hospital2Dep4'),
    path("hospital2-dep4-doc1-consultation", views.hospital2Dep4Doc1Consultation, name='hospital2Dep4Doc1Consultation'),
    path("hospital2-dep4-doc1-reservation", views.hospital2Dep4Doc1Reservation, name='hospital2Dep4Doc1Reservation'),
    path("hospital2-dep4-doc2-consultation", views.hospital2Dep4Doc2Consultation, name='hospital2Dep4Doc2Consultation'),
    path("hospital2-dep4-doc2-reservation", views.hospital2Dep4Doc2Reservation, name='hospital2Dep4Doc2Reservation'),
    path("signin", views.signin, name='signin'),
    path("main-hospital1", views.mainHos1, name='mainHos1'),
    path("main-hospital2", views.mainHos2, name='mainHos2'),
    path("main", views.main, name='main'),
    path("main-admin", views.mainAdmin, name='mainAdmin'),
    path("show-consultation", views.showConsultation, name='showConsultation'),
    path("show-reservation", views.showReservation, name='showReservation'),
    path("signup", views.signup, name='signup'),
    path("logout", views.logout_view, name='logout'),
    
    path("hospitals/", HospitalListAPIView.as_view()),
    path("sections/", HospitalSectionListAPIView.as_view()),
    path("doctors/", DoctorListAPIView.as_view()),
    path("register/", UserRegisterView.as_view()),
    path("login/", LoginView.as_view()),
    path("doctor-details/", DoctorDetailsView.as_view()),
    path("my-reservations/", MyReservationsView.as_view()),
    path("my-consulations/", MyConsultationsView.as_view()),
    path("my-consulations/<int:pk>/", ReplyToConsultationView.as_view()),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL)
